# Set the workflow name.
name: CI

# Execute the workflow on pushes.
on: push

# Define the workflow jobs
jobs:
  macos:
    name: Test Install
    runs-on: macos-latest
    steps:
      - run: brew install mutagen-io/mutagen/mutagen mutagen-io/mutagen/mutagen-compose
      - run: brew uninstall mutagen mutagen-compose
      - run: brew install mutagen-io/mutagen/mutagen-beta mutagen-io/mutagen/mutagen-compose-beta
      - run: brew uninstall mutagen-beta mutagen-compose-beta
      - run: brew install mutagen-io/mutagen/mutagen-edge
      - run: brew uninstall mutagen-edge
